In [1]:
import numpy as np

In [3]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [4]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

이게바로 연산을 쉽게해주는 거군!

In [7]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [9]:
array3 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [10]:
array3 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [14]:
array3 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [16]:
booleans = np.array([True,True,False,True,True,False,True,True,True,False,True])

In [17]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [20]:
np.where(array3 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [21]:
filter = np.where(array3>4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [22]:
array3[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [23]:
print(array3.max())
print(array3.min())

31
2


In [24]:
print(array3.mean())

14.545454545454545
