In [5]:
import numpy

In [6]:
array1 = numpy.full(6,7)

In [7]:
print(array1)

[7 7 7 7 7 7]


In [8]:
array2 = numpy.zeros(7,dtype=int)
print(array2)

[0 0 0 0 0 0 0]


In [16]:
array3 = numpy.ones(5,dtype=int)
print(array3)

[1 1 1 1 1]


위에꺼는 zero랑 one만 됩니다

In [17]:
random1 = numpy.random.random(6)
random2 = numpy.random.random(6)
print(random1)
print(random2)

[0.5000806  0.38073391 0.30192354 0.86786915 0.84151607 0.74317195]
[0.19835961 0.15145924 0.71443488 0.48466182 0.9700596  0.31850445]


In [18]:
range1 = numpy.arange(6)
print(range1)

[0 1 2 3 4 5]


In [19]:
range2 = numpy.arange(1,10)
print(range2)

[1 2 3 4 5 6 7 8 9]


In [21]:
range3 = numpy.arange(1,20,2)
print(range3)

[ 1  3  5  7  9 11 13 15 17 19]
