In [2]:
import numpy as np

In [10]:
array1 = np.array([2,3,4,7,11,13,17,19,23,29,31])

In [11]:
array2 = np.array([1,2,3])

In [12]:
array1[array2]

array([3, 4, 7])

In [13]:
array1[0:5]

array([ 2,  3,  4,  7, 11])

In [14]:
array1[2:]

array([ 4,  7, 11, 13, 17, 19, 23, 29, 31])

In [15]:
array1[2:12:2]

array([ 4, 11, 17, 23, 31])

In [4]:
array5[0]

2

In [5]:
array5[[1,3,4]]

array([ 3,  7, 11])

In [8]:
array6 = np.array([2,1,3])

In [9]:
array5[array6]

array([4, 3, 7])